# Generated by Django 5.1.3 on 2024-11-15 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='buyer',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(120)]),
        ),
    ]
